#!/bin/bash

REV=$(svn up|awk '{print $3'})
REV=${REV%.*}

mkdir -p /media/LinuxData/Development/PKGS/ClipboardViewer

make install DESTDIR=/media/LinuxData/Development/PKGS/ClipboardViewer

ln -sf /media/LinuxData/Development/PKGS/ClipboardViewer/usr/local/share/ClipboardViewer/scripts/MakeClipping ~/.gnome2/nautilus-scripts
cd /media/LinuxData/Development/PKGS/ClipboardViewer
/sbin/makepkg -l y -c n ../ClipboardViewer-svn-rev-$REV-X86_64-1.tgz
