#!/bin/bash -e

#©keithhedger Wed 22 May 19:55:26 BST 2013 kdhedger68713@gmail.com

VERSION=$(head ./configure.ac|grep AC_INIT|awk -F [ '{print $3}'|awk -F ] '{print $1}')

svn commit -m ""
pushd /tmp
svn co file:///media/LinuxData/Development/SVN/AspellGUI
find ClipboardViewer -name ".svn" -exec rm -r '{}' \; || true
rm /tmp/ClipboardViewer/makepkg
mv /tmp/ClipboardViewer /tmp/ClipboardViewer-${VERSION}

cd /tmp/ClipboardViewer-${VERSION}

./remakesourcelist
aclocal
autoheader
touch NEWS README AUTHORS ChangeLog
automake --add-missing --copy
autoconf

rm -rf ./autom4te.cache
rm ./compile ./missing ./COPYING ./AUTHORS ./NEWS
cd ..

tar -czvf ClipboardViewer-${VERSION}.tar.gz ClipboardViewer-${VERSION}
rm -r /tmp/ClipboardViewer-${VERSION}
popd
cp /tmp/ClipboardViewer-${VERSION}.tar.gz .