#!/bin/bash -e

VERSION=1.50.0

cd /tmp
svn co file:///media/LinuxData/Development/SVN/ClipboardViewer
cd /tmp/ClipboardViewer
find . -iname .svn -exec rm -rf '{}' \; || true
./configure
make
make distclean
cd ..
tar --exclude="makezip" --exclude="makepkg" -cvzf ClipboardViewer-${VERSION}.tar.gz ./ClipboardViewer
rm -rf ./ClipboardViewer
