#!/bin/bash

REV="$(svn status -u|awk '{ print $4 }')"
echo "xxx$REV-ccc"
exit
cp -r . /tmp/ClipboardViewer
cd /tmp/ClipboardViewer
echo "xxx$REV-ccc"
find . -iname .svn -exec rm -rf '{}' \;
cd ..
tar --exclude="makezip" -cvzf ClipboardViewer.${REV}.tgz ./ClipboardViewer

