#!/bin/bash -e

VERSION=1.50.0

cd /tmp
svn co file:///media/LinuxData/Development/SVN/ClipboardViewer
cd /tmp/ClipboardViewer
find . -iname .svn -exec rm -rf '{}' \; || true
cd ..
tar --exclude="makezip" -cvzf ClipboardViewer.${VERSION}.tgz ./ClipboardViewer

