.\" clipboardviewer
.TH "clipboardviewer" "1" "1.0.35" "K.D.Hedger" "User Commands"
.SH "NAME"
clipboardviewer \- manual page for clipboardviewer 1.0.35
.SH "SYNOPSIS"
.B clipboardviewer
[\fI\-\-nogui\fR]
[\fI\-\-query\fR]
.SH "DESCRIPTION"
A GUI to view the main clipboard contents ( text or pic ) or from the command line print the text contents to stdin or create a .png image file in the current directory.
The window is persistant and will be updated regularly.

.TP 
\fB\-\-nogui\fR Do not create a window just print the contents to stdin or create a picture in the current folder
.TP 
\fB\-\-query\fR Print type of data on clipboard ( image or text )
.SH "EXAMPLES"
.LP 
Show the main clipboard window
.IP 
clipboardviewer
.LP 
Print the contents of the clipboard to stdin or create a file in the current directory
.IP 
clipboardviewer \-\-nogui
.LP 
Print the type of data on the clipboard ( text or image )
.IP 
clipboardviewer \-\-query
.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
